/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/lixiao/Desktop/MBot/src/multirobot_localization/msg/motor_ctr.msg
 *
 */


#ifndef MULTIROBOT_LOCALIZATION_MESSAGE_MOTOR_CTR_H
#define MULTIROBOT_LOCALIZATION_MESSAGE_MOTOR_CTR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace multirobot_localization
{
template <class ContainerAllocator>
struct motor_ctr_
{
  typedef motor_ctr_<ContainerAllocator> Type;

  motor_ctr_()
    : header()
    , left_wheel(0.0)
    , right_wheel(0.0)  {
    }
  motor_ctr_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left_wheel(0.0)
    , right_wheel(0.0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _left_wheel_type;
  _left_wheel_type left_wheel;

   typedef double _right_wheel_type;
  _right_wheel_type right_wheel;




  typedef boost::shared_ptr< ::multirobot_localization::motor_ctr_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::multirobot_localization::motor_ctr_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct motor_ctr_

typedef ::multirobot_localization::motor_ctr_<std::allocator<void> > motor_ctr;

typedef boost::shared_ptr< ::multirobot_localization::motor_ctr > motor_ctrPtr;
typedef boost::shared_ptr< ::multirobot_localization::motor_ctr const> motor_ctrConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::multirobot_localization::motor_ctr_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::multirobot_localization::motor_ctr_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace multirobot_localization

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/home/lixiao/ros_catkin_ws/install_isolated/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/home/lixiao/ros_catkin_ws/install_isolated/share/geometry_msgs/cmake/../msg'], 'multirobot_localization': ['/home/lixiao/Desktop/MBot/src/multirobot_localization/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::multirobot_localization::motor_ctr_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multirobot_localization::motor_ctr_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multirobot_localization::motor_ctr_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multirobot_localization::motor_ctr_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multirobot_localization::motor_ctr_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multirobot_localization::motor_ctr_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::multirobot_localization::motor_ctr_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3b8f6c33f8aa9ab11781a2a0e65b64dc";
  }

  static const char* value(const ::multirobot_localization::motor_ctr_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3b8f6c33f8aa9ab1ULL;
  static const uint64_t static_value2 = 0x1781a2a0e65b64dcULL;
};

template<class ContainerAllocator>
struct DataType< ::multirobot_localization::motor_ctr_<ContainerAllocator> >
{
  static const char* value()
  {
    return "multirobot_localization/motor_ctr";
  }

  static const char* value(const ::multirobot_localization::motor_ctr_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::multirobot_localization::motor_ctr_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float64 left_wheel\n\
float64 right_wheel\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::multirobot_localization::motor_ctr_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::multirobot_localization::motor_ctr_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left_wheel);
      stream.next(m.right_wheel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct motor_ctr_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::multirobot_localization::motor_ctr_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::multirobot_localization::motor_ctr_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left_wheel: ";
    Printer<double>::stream(s, indent + "  ", v.left_wheel);
    s << indent << "right_wheel: ";
    Printer<double>::stream(s, indent + "  ", v.right_wheel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MULTIROBOT_LOCALIZATION_MESSAGE_MOTOR_CTR_H
